services:
  - type: web
    name: 1dollardayitinerary-api
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install && npx puppeteer browsers install chrome && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
      - key: CHROME_PATH
        value: "/opt/render/.cache/puppeteer/chrome/linux-127.0.6533.88/chrome-linux64/chrome"
