services:
  - type: web
    name: 1dollardayitinerary-api
    env: node
    plan: free
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm start
    envVars:
      - key: NODE_ENV
        value: production 